# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/spagi002/final-project-snand021

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/spagi002/final-project-snand021

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/spagi002/final-project-snand021/CMakeFiles /home/csmajs/spagi002/final-project-snand021//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/spagi002/final-project-snand021/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.cpp

# Build rule for target.
main.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main.cpp
.PHONY : main.cpp

# fast build rule for target.
main.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/build
.PHONY : main.cpp/fast

#=============================================================================
# Target rules for targets named runAllTests

# Build rule for target.
runAllTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runAllTests
.PHONY : runAllTests

# fast build rule for target.
runAllTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/build
.PHONY : runAllTests/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Menu.o: Menu.cpp.o
.PHONY : Menu.o

# target to build an object file
Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/Menu.cpp.o
.PHONY : Menu.cpp.o

Menu.i: Menu.cpp.i
.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s
.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

Remind.o: Remind.cpp.o
.PHONY : Remind.o

# target to build an object file
Remind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/Remind.cpp.o
.PHONY : Remind.cpp.o

Remind.i: Remind.cpp.i
.PHONY : Remind.i

# target to preprocess a source file
Remind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/Remind.cpp.i
.PHONY : Remind.cpp.i

Remind.s: Remind.cpp.s
.PHONY : Remind.s

# target to generate assembly for a file
Remind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/Remind.cpp.s
.PHONY : Remind.cpp.s

task.o: task.cpp.o
.PHONY : task.o

# target to build an object file
task.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/task.cpp.o
.PHONY : task.cpp.o

task.i: task.cpp.i
.PHONY : task.i

# target to preprocess a source file
task.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/task.cpp.i
.PHONY : task.cpp.i

task.s: task.cpp.s
.PHONY : task.s

# target to generate assembly for a file
task.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/task.cpp.s
.PHONY : task.cpp.s

taskList.o: taskList.cpp.o
.PHONY : taskList.o

# target to build an object file
taskList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/taskList.cpp.o
.PHONY : taskList.cpp.o

taskList.i: taskList.cpp.i
.PHONY : taskList.i

# target to preprocess a source file
taskList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/taskList.cpp.i
.PHONY : taskList.cpp.i

taskList.s: taskList.cpp.s
.PHONY : taskList.s

# target to generate assembly for a file
taskList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/taskList.cpp.s
.PHONY : taskList.cpp.s

test/taskListtest.o: test/taskListtest.cpp.o
.PHONY : test/taskListtest.o

# target to build an object file
test/taskListtest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/taskListtest.cpp.o
.PHONY : test/taskListtest.cpp.o

test/taskListtest.i: test/taskListtest.cpp.i
.PHONY : test/taskListtest.i

# target to preprocess a source file
test/taskListtest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/taskListtest.cpp.i
.PHONY : test/taskListtest.cpp.i

test/taskListtest.s: test/taskListtest.cpp.s
.PHONY : test/taskListtest.s

# target to generate assembly for a file
test/taskListtest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/taskListtest.cpp.s
.PHONY : test/taskListtest.cpp.s

test/testViewSchedule.o: test/testViewSchedule.cpp.o
.PHONY : test/testViewSchedule.o

# target to build an object file
test/testViewSchedule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/testViewSchedule.cpp.o
.PHONY : test/testViewSchedule.cpp.o

test/testViewSchedule.i: test/testViewSchedule.cpp.i
.PHONY : test/testViewSchedule.i

# target to preprocess a source file
test/testViewSchedule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/testViewSchedule.cpp.i
.PHONY : test/testViewSchedule.cpp.i

test/testViewSchedule.s: test/testViewSchedule.cpp.s
.PHONY : test/testViewSchedule.s

# target to generate assembly for a file
test/testViewSchedule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/testViewSchedule.cpp.s
.PHONY : test/testViewSchedule.cpp.s

test/test_rem.o: test/test_rem.cpp.o
.PHONY : test/test_rem.o

# target to build an object file
test/test_rem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/test_rem.cpp.o
.PHONY : test/test_rem.cpp.o

test/test_rem.i: test/test_rem.cpp.i
.PHONY : test/test_rem.i

# target to preprocess a source file
test/test_rem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/test_rem.cpp.i
.PHONY : test/test_rem.cpp.i

test/test_rem.s: test/test_rem.cpp.s
.PHONY : test/test_rem.s

# target to generate assembly for a file
test/test_rem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/test_rem.cpp.s
.PHONY : test/test_rem.cpp.s

test/userTests.o: test/userTests.cpp.o
.PHONY : test/userTests.o

# target to build an object file
test/userTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/userTests.cpp.o
.PHONY : test/userTests.cpp.o

test/userTests.i: test/userTests.cpp.i
.PHONY : test/userTests.i

# target to preprocess a source file
test/userTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/userTests.cpp.i
.PHONY : test/userTests.cpp.i

test/userTests.s: test/userTests.cpp.s
.PHONY : test/userTests.s

# target to generate assembly for a file
test/userTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTests.dir/build.make CMakeFiles/runAllTests.dir/test/userTests.cpp.s
.PHONY : test/userTests.cpp.s

viewSchedule.o: viewSchedule.cpp.o
.PHONY : viewSchedule.o

# target to build an object file
viewSchedule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/viewSchedule.cpp.o
.PHONY : viewSchedule.cpp.o

viewSchedule.i: viewSchedule.cpp.i
.PHONY : viewSchedule.i

# target to preprocess a source file
viewSchedule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/viewSchedule.cpp.i
.PHONY : viewSchedule.cpp.i

viewSchedule.s: viewSchedule.cpp.s
.PHONY : viewSchedule.s

# target to generate assembly for a file
viewSchedule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/viewSchedule.cpp.s
.PHONY : viewSchedule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... main.cpp"
	@echo "... runAllTests"
	@echo "... Menu.o"
	@echo "... Menu.i"
	@echo "... Menu.s"
	@echo "... Remind.o"
	@echo "... Remind.i"
	@echo "... Remind.s"
	@echo "... task.o"
	@echo "... task.i"
	@echo "... task.s"
	@echo "... taskList.o"
	@echo "... taskList.i"
	@echo "... taskList.s"
	@echo "... test/taskListtest.o"
	@echo "... test/taskListtest.i"
	@echo "... test/taskListtest.s"
	@echo "... test/testViewSchedule.o"
	@echo "... test/testViewSchedule.i"
	@echo "... test/testViewSchedule.s"
	@echo "... test/test_rem.o"
	@echo "... test/test_rem.i"
	@echo "... test/test_rem.s"
	@echo "... test/userTests.o"
	@echo "... test/userTests.i"
	@echo "... test/userTests.s"
	@echo "... viewSchedule.o"
	@echo "... viewSchedule.i"
	@echo "... viewSchedule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

